### PR TITLE
Apple Fix

### PR DESCRIPTION
**Pull request by mboneil10**
So apple doesn't reject our build. The second half (reasoning for accessing location) is done in xCode:
https://stackoverflow.com/questions/47749667/add-description-to-permission-modal-alert

### CODE REVIEW

**Comment by werebus** [comment]
So, if there _is_ an appeal button to click, I would definitely favor that over this change. In my opinion, this is clearly a false-positive — the concept of "contributing" to open-source software is not some sort of new and foreign concept. I have no particular interest in whether or not anyone "views" our source code (although it's nice that they can). What I would love is if they opened issues, forked the code, or opened PRs.

---

On the second part, we should find some way to persist those plist values in our source code somewhere. Otherwise, we'll likely hit this stumbling block again if someone else builds the iOS app, or even if you get a new laptop at some point. You can [use a hook][1] to copy values from `config.xml` into `*-Info.plist` and `AndroidManifest.xml` files. Alternatively, for a less general (but better maintained) solution, the plugin discussed in #474 takes care of these [two specific plist values][2] for you.

[1]:  https://geeklearning.io/how-to-add-specific-configuration-parameters-to-ios-p-list-and-android-manifest/
[2]:  https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/293815d811f3bfe8febd95287cf1a6d23b665846#install-optional-variables

**Review by Anbranin — COMMENTED** [review]
I think what @werebus said in Slack:

> Yeah, but what we want is for them to feel encouraged to contribute to our open-source project. Not passively view some code

What about adding the word code in there? "Contribute to PVTrAck source code" ?
Or do you think that's unnecessary? I want to encourage people to help with this project, so adding the word "code" somehow is good

**Comment by werebus** [comment]
I also want to temper my philosophical objection with some facts too. I think a more active sounding "call to action" is a good thing :tm:, but also only 12 people have exited the site via that page in the last year. Some of those 12 went to GitHub, but some of them could have ended up on the Wikipedia page for "Compassion."

**Comment by mboneil10** [comment]
Okie dokie, I'll close this. I will submit an appeal for the first portion, and use a hook for the second part. Thanks @werebus. For the long term solution, I'll square away a day to get the plugin done.

**Pull request closed without merging**
