### PR TITLE
View Updates for Route Page

### PR DESCRIPTION
**Pull request by akaplo**
Revamps the Route UI.  Flattens out the vehicle list and expands the stop list using a Timeline-style  display.  Moves the Map This Route button from a bar on the bottom to the bar on top, and removes the Map button for Vehicles (and removes the entire `vehicle-map` state).

@sherson I know some of these changes were things you were looking for, so I'm interested to hear your thoughts specifically.

**Before:**

image

**After**

image

### CODE REVIEW

**Comment by petermarathas** [comment]
Awesome

**Comment by sherson** [comment]
Looks good, though in my opinion, the stops list would look cleaner without the boxes and clock/location icons.

**Comment by akaplo** [comment]
@sherson After much thought, I agree with you.  I'm going to take that out and leave it just as the list, but I think keeping it always expanded and sorted by Avail's SortOrder will stay.

**Comment by akaplo** [comment]
CC failures are OK.

**Comment by akaplo** [comment]
@sherson here's a new screenshot.  I think we're ready to merge this upon your goahead.
image

**Comment by sherson** [comment]
Looks good to me

**Pull request merged**
