### PR TITLE
RouteController Rework

### LINKED ISSUE #82: Change Route Page
@dfaulken brings up a good point that the Route page won't be particularly useful for normal passengers.

Ideas include putting a map that has the trace and each bus at the top of the page. Anything else?

### PR DESCRIPTION
**Pull request by akaplo**
Closes #82.  Adds a map that shows buses and a KML to the route page.  

Also simplifies the details given for each bus (we'll leave more details to the VehicleController) and fixes a bug where, when a route had a long list of stops, the page slowed to a crawl.  This was fixed by using an `ion-scroll-view`.

There are a few other UI tweaks, but I'll leave that to the screenshots:
screen shot 2016-04-01 at 6 35 46 pm
screen shot 2016-04-01 at 6 36 02 pm

### CODE REVIEW

**Comment by bgregg** [comment]
I am not sure if this PR fixes this bug, but in master right now stops are not clickable from the route page.

**Comment by akaplo** [comment]
It does.

**Comment by akaplo** [comment]
Note that this pull request contains but _does not fix_ #124

**Comment by akaplo** [comment]
Hearing no complaints, I'm merging this.

**Pull request merged**
