### PR TITLE
Add cooperative gesture handling for maps on plan trip

### LINKED ISSUE #397: Schedule Page Map Single Scroll
I click on the schedule page and scroll up. However, instead of scrolling further up on the page, I zoom in on the map (for both mobile and desktop). My work around: Dodge the map and continue scrolling on the screen above it.

Basically, scrolling on this page can't be done in one fluid motion. The way I'd fix this is to shrink the map so it doesn't stretch across the page. Or disable zooming unless the map is touched.  

 I don't know if this is a personal problem or if other users experience the same pain as I do.

### PR DESCRIPTION
**Pull request by akaplo**
Closes #397.  Adds "cooperative gesture handling" from the [Maps API](https://developers.google.com/maps/documentation/javascript/interaction#gesture-handling).  Users will be familiar with this as "that annoying thing that makes me use two fingers to move the map," but I'm convinced this is better than what we had before.

When scrolling down the Schedule page after planning a trip, you'll see this (**applies to touch-based devices only**):
image

Confirmed working on my Nexus with mobile-Chrome 58 and has no effect on my Mac on Chrome 59.  @dfaulken, I know you don't know anything about pvtrack testing, but would you anticipate an integration test might be able to check functionality for this?

### CODE REVIEW

**Comment by dfaulken** [comment]
In generic terms, yes, mobile-centered integration tests would hopefully be able to spot a difference in functionality here.

**Review by mboneil10 — APPROVED** [review]
I didn't know that people dislike using two fingers to move the map. Anyway, this is great!

**Review by Anbranin — APPROVED** [review]

**Comment by akaplo** [comment]
I'm gonna see if I can write a test for this before merging.

**Comment by akaplo** [comment]
I unfortunately don't know how to test this. I'll open an issue for it though and will continue to read about how to do so.  In the meantime, this works.

**Pull request merged**
