### PR TITLE
Capistrano configuration to deploy to app3

### PR DESCRIPTION
**Pull request by werebus**

### CODE REVIEW

**Comment by akaplo** [comment]
Nothing here looks out of place to me, so I'll approve and defer to your judgment on its readiness.
Thanks @werebus! Let me know if there's anything you need from me.

**Review by akaplo — APPROVED** [review]

**Comment by werebus** [comment]
I'm particularly interested in whether the key.js stuff looks correct.

There's probably a bit of a performance impact, but the maps key at least works on development. That said, it's probably the first JavaScript I've written all year.

**Comment by werebus** [comment]
Before this is merged, I *do* have a few operational things to make sure are in place.

**Comment by akaplo** [comment]
OK. I had a comment, but I forgot what it was. Will think and get back to
you.

**Pull request merged**
