### PR TITLE
Walking directions

### PR DESCRIPTION
**Pull request by Anbranin**
Google does not provide arrival and departure times when public transit is not involved in a trip (so, if you're only walking). The app tried to fetch arrival and departure times anyways, so on trips where there was only walking (so from here to the campus store, for example), an error would be thrown trying to fetch a null value.
Put an ngIf in there to check for existence and fetched those values only if they are present.

### CODE REVIEW

**Review by werebus — COMMENTED** [review]
So, to confirm, users *do* get walking directions still?

**Comment by Anbranin** [comment]
They absolutely do get walking directions.

**Comment by akaplo** [comment]
Travis is failing because of #378.  Let's roll a fix for that into this PR.  Far as I can tell, the fix should be in [travis.yml](https://github.com/umts/pvta-multiplatform/blob/master/.travis.yml#L30) and the README, wherein we have two options:

1. Specify `npm install -g ionic@^2.21` and remove [your changes to package.json](https://github.com/umts/pvta-multiplatform/pull/377/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R54), or
2. Specify `npm install -g ionic@^3.0.0` and keep your changes to package.json.  (since Travis got the new version of ionic and should be using your package.json, I'm not sure why it didn't install the plugin and succeed in the first place though?)

**Review by akaplo — CHANGES_REQUESTED** [review]
We should figure out how to deal with the new version of Ionic's CLI and Travis.

**Review by akaplo — APPROVED** [review]

**Pull request merged**
