### PR TITLE
Tappable Favorite Routes

### LINKED ISSUE #417: "Edit Favorite Routes": Items should be tappable
The list items on "Edit Favorite Routes" should be tappable to select the checkbox on the left. (similar to "Edit Favorite Stops")

### PR DESCRIPTION
**Pull request by mboneil10**
Closes #417

### CODE REVIEW

**Comment by mboneil10** [comment]
The problem was with the columns not being tappable. Alternatively, I could have made the columns tappable and made the `click` event link to checking the checkbox. Whatever people like more. Personally, I like how I did it better.

**Comment by mboneil10** [comment]
screen shot 2017-10-03 at 9 44 55 am

**Comment by mboneil10** [comment]
screen shot 2017-10-03 at 9 46 09 am

**Comment by mboneil10** [comment]
Compare with 
screen shot 2017-10-03 at 9 47 40 am

screen shot 2017-10-03 at 9 48 36 am

**Comment by mboneil10** [comment]
The columns make the text align, but the huge white space in between is kind of weird.

**Comment by mboneil10** [comment]
Did I make an oops? @akaplo

**Comment by akaplo** [comment]
Yeah, making them `<div>`s removed all the flexbox spacing the `ion-col`s were giving you for free.

I think the real issue has to do with how the [row and columns](https://github.com/umts/pvta-multiplatform/blob/master/src/modals/route-modal/route.modal.html#L20) exist inside the `ion-label`.

**Comment by mboneil10** [comment]
Confusion with messages. However, this version now works.

**Review by Anbranin — APPROVED** [review]

**Pull request merged**
