### PR TITLE
Ionic 3

### LINKED ISSUE #406: Ionic 3
**EDIT 8/3/17** Either I was misunderstanding from the beginning or they fixed this in some updates to 3.x, but most of what I believed was barring us from upgrading was simply untrue.  See #413.

**ORIGINAL**
Ionic 3 has been stable for almost 2 months.  There's a single major roadblock for us to update to it: routing.  We use explicit URLs (/favorites, /settings, etc) like a website, which Ionic has decided to make significantly harder.

In order to use this kind of routing, we must use their [IonicPage](http://ionicframework.com/docs/api/navigation/IonicPage/) and "Lazy Loading" features, which require a separate module for each page (instead of just an `app.module.ts`, we'd need to add a `page_name.module.ts` for each page in the app), which in my opinion is a ridiculous design choice that creates a lot of unnecessary code replication.

See [part 1](http://blog.ionic.io/ionic-and-lazy-loading-pt-1/) and [part 2](http://blog.ionic.io/ionic-and-lazy-loading-pt-2/) of a 2-part official post on the topic.

So, what I'm interested in determining is: should we just stick with Ionic 2.x?  Bite the bullet, take the duplication hit and keep moving with Ionic?  Or, change how we think about our routing?

### PR DESCRIPTION
**Pull request by mboneil10**
Closes #406, #389

### CODE REVIEW

**Comment by mboneil10** [comment]
Did I do this correctly? Idk if `ionic-angular` should have changed. `ionic` is up to 3.6.0, though.

>  cli packages:
> 
>     @ionic/cli-plugin-cordova       : 1.5.0 (/Users/molly/pvta-multiplatform/node_modules/@ionic/cli-plugin-cordova)
>     @ionic/cli-plugin-ionic-angular : 1.4.0 (/Users/molly/pvta-multiplatform/node_modules/@ionic/cli-plugin-ionic-angular)
>     @ionic/cli-utils                : 1.6.0 (/Users/molly/pvta-multiplatform/node_modules/@ionic/cli-utils)
>     ionic (Ionic CLI)               : 3.6.0 (/Users/molly/pvta-multiplatform/node_modules/ionic)
> 
> global packages:
> 
>     Cordova CLI : 7.0.1
> 
> local packages:
> 
>     @ionic/app-scripts : 1.3.8
>     Cordova Platforms  : none
>     Ionic Framework    : ionic-angular 2.2.0
>

**Comment by akaplo** [comment]
This is definitely a start. Here are some resources that might help you figure out if you've missed anything:

https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md#300-2017-04-05
https://docs.google.com/document/d/1vGokwMXPQItZmTHZQbTO4qwj_SQymFhRS_nJmiH0K3w
https://forum.ionicframework.com/t/guide-how-to-update-to-ionic-3-x/87516

**Comment by mboneil10** [comment]
Thanks @akaplo. I checked out all the links and two have the same basic four steps that I followed. But maybe I should add Lazy Loading too. (from that second link)

Edit: you're totally right. Several more steps to this process. Currently at 3.0.0 in terms of packages and stuffs. Will make it to 3.6.0 by the end of today, mark my words!!

**Comment by mboneil10** [comment]
OK. Looked some stuff up. Apparently they've changed grid attributes that will be [deprecated](http://blog.ionic.io/build-awesome-desktop-apps-with-ionics-new-responsive-grid/). I'll be looking for these attributes and get rid of them right meow. 

For other changes, I'm looking at the [changelog](https://github.com/ionic-team/ionic/blob/master/CHANGELOG.md).

**Comment by akaplo** [comment]
Great!  I was gonna suggest making it work on 3.0 and then bumping up to 3.6 and worrying about lazyloading and URL schemes then, but it seems like that's already your plan! I'm currently installing your branch from scratch so I'll let you know if I run into any issue when I try to run it.

**Comment by akaplo** [comment]
1 npm warning:
```
npm WARN @angular/platform-server@4.0.0 requires a peer of @angular/animations@4.0.0 but none was installed.
```

**Comment by mboneil10** [comment]
Yeah, idk what to do with those npm warnings.

**Comment by mboneil10** [comment]
@akaplo will take the upgrade from 2.x to 3.0 and remove URL routing. His explanation: "the jump from 2.x to 3.0 completely changed the way Ionic does URL routing." We've been using a supported workaround, but the app won't compile unless it's changed.

In the meantime, I'll make the jump from 3.0 to 3.6. In small steps.

We'll meet back and fix the routing together.

**Comment by mboneil10** [comment]
We'll work off a different branch together. Closing until we get somewhere.

**Pull request closed without merging**
