### PR TITLE
Drop seconds for EDT

### LINKED ISSUE #438: We don't round off secret seconds early enough
screenshot_20170922-135318

It's weird to say that 1:54 PM is in both one and two minutes. Presumably this comes from the Avail side in the form of an EDT including seconds. Seems like we should round that off before using the estimation, to avoid this weirdness.

### PR DESCRIPTION
**Pull request by mboneil10**
Closes #438

### CODE REVIEW

**Comment by mboneil10** [comment]
Before
screen shot 2017-11-13 at 3 58 17 pm


After
screen shot 2017-11-13 at 3 57 58 pm

**Comment by mboneil10** [comment]
Did I do this correctly? Or should the `EDT` change to `4:01 PM` in the above case?

**Comment by dfaulken** [comment]
> Did I do this correctly? Or should the `EDT` change to `4:01 PM` in the above case?

We should drop seconds from both the current time and the EDT/SDT ~when~ before calculating an interval. Does this do that?

**Comment by mboneil10** [comment]
No, it only drops seconds for EDT. I'll do it for SDT too.

**Comment by dfaulken** [comment]
Question: if the current time is 2:00:59 PM, and we trim the EDT to 2:06:00 PM, how does moment's `fromNow` display that? 6 minutes? or 5 minutes?

**Comment by mboneil10** [comment]
@dfaulken I don't know and I'm unsure of how to check.

**Comment by dfaulken** [comment]
I think the best way is to insert a debugger into the relevant code and construct some of your own `moment` objects.

**Comment by mboneil10** [comment]
To answer your question from three months ago, @dfaulken...
the situation you described displays five minutes.

I did some bs in the code:
```
     const a = moment('2016-01-01 14:00:59');
     const b = moment('2016-01-01 14:06:00');
     console.log(a.from(b));
```

Produced:
`console.log: 5 minutes ago`

Assuming that `from(now)` is equivalent to `fromNow`, anyway.

**Review by dfaulken — APPROVED** [review]
Great.

**Comment by mboneil10** [comment]
All that for two lines of code to change.

**Review by werebus — APPROVED** [review]

**Comment by dfaulken** [comment]
A very *important* two lines 😛

**Pull request merged**
