### PR TITLE
Perhaps fix codeclimate tslint config?

### PR DESCRIPTION
**Pull request by werebus**
I'm not sure if this will fix our codeclimate issue, but I have to make a PR to see. Don't merge just yet...

### CODE REVIEW

**Comment by mboneil10** [comment]
Codeclimate issue?

**Comment by werebus** [comment]
image

https://codeclimate.com/github/umts/pvta-multiplatform/builds

**Comment by werebus** [comment]
Alright, it looks like the PR build is working: https://codeclimate.com/github/umts/pvta-multiplatform/builds/755

Now lets see how this looks on master...

**Review by mboneil10 — APPROVED** [review]
Ok, sweet! Let's see how it works.

**Pull request merged**
