### PR TITLE
Rework Stop Dropdown

### PR DESCRIPTION
**Pull request by akaplo**
Inspired by a fellow driver who was baffled when I showed her that you could tap on a departure and you'd see more of them, I decided to make some changes.

For reference, the Stop page looks like this currently:

image

When you expand a route (which is not even an obvious option), it looks like this:
image

I redid the format of the rows (both on the main Route bars, and their departure dropdowns).  The main bar now has the almighty "arrow thingy," and the dropdown is much more compact.

Here's the new version:

image

And expanded:

image

### CODE REVIEW

**Comment by akaplo** [comment]
@reviewers, I'm interested especially in your UI thoughts.  In particular: route's color as the dropdown background, yay or nay?

**Comment by sherson** [comment]
Arrow looks good. I think I slightly prefer the white drop-down over the matching color drop-down, but both seem fine to me.

**Comment by werebus** [comment]
Agreed. White background is better (IMO); that's a big block of pink.

Alternately, maybe a less-saturated version of the route color, You can achieve that with [CSS `filter`s](https://developer.mozilla.org/en-US/docs/Web/CSS/filter?v=example), I guess?  Although support is [a little spotty](http://caniuse.com/#feat=css-filters).

**Comment by Anbranin** [comment]
@akaplo Should I finish this? I actually concur with both these people.

**Comment by akaplo** [comment]
@Anbranin I'm more than fine with you finishing this off; should be pretty easy for you. If you need help, just hit me up on Slack like always, I'm around.

**Comment by mboneil10** [comment]
What has happened to this? @akaplo, @Anbranin. (Just curious) Because I don't understand why it's open if nothing is going on.

**Comment by Anbranin** [comment]
...oops

**Comment by akaplo** [comment]
Closing for now, see #407.

**Pull request closed without merging**
