### PR TITLE
Animate StopMap Directions

### PR DESCRIPTION
**Pull request by akaplo**
I'm trying to learn anything about CSS animations, so this is a start (the gif is a little choppy btw).

slide

### CODE REVIEW

**Comment by mboneil10** [comment]
Let me know when you want me to look this over @akaplo

**Comment by akaplo** [comment]
lol @mboneil10 it's ready when you are - I just animated the bottom bar sliding in/out using CSS.

**Comment by mboneil10** [comment]
Ah, okay. I was confused when you said "this is a start." Wasn't sure if the view would stay the same but the code would change.

**Comment by mboneil10** [comment]
This isn't related to any issue, correct? Did you make this change because you wanted the map to be fullscreen and allow the user to pull up the StopMap directions?

**Comment by akaplo** [comment]
~~Correct~~ sorry, no.  I made it because the screen currently just juts up and this smooths out the interaction.

**Comment by akaplo** [comment]
@mboneil10 any reason not to merge this? It's just a nice animation for the StopMap page when you request directions.

**Review by mboneil10 — APPROVED** [review]

**Comment by mboneil10** [comment]
Nah, I just forgot about it. Good job at animations, Aaron.

**Comment by akaplo** [comment]
Ah, no worries.  Thanks!

**Pull request merged**
